-- liquibase formatted sql
-- changeset zuhaimi:1677359720411-3
CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT "departmentPK" PRIMARY KEY (id)
);

